### ISSUE TITLE
wrong returned status

### ISSUE THREAD

**Issue by ricoud** [NicolasSiver/nodebb-plugin-ns-api#1]
Hello,
the returned status of the `api/v1/users/:uid` route is always **online** 

api/v1/users/15 returns `"status": "online"`
while 
api/user/bonjour returns `"status":"offline","uid":15`

Thanks

**Comment by NicolasSiver** [comment]
`api/user/bonjour` ? 
Could you share an url on the source code, about `/bonjour` implementation?

**Comment by ricoud** [comment]
'bonjour' is the name I gave to one user on my dev environment.
So `api/user/bonjour` is the url of the standard nodebb url `api/user/userslug` which gives information about a user.
Anyway all tested routes `api/v1/users/:uid` return user status as online even if I'm the only logged user.
Thanks for your time

**Comment by NicolasSiver** [comment]
@ricoud hm, I'm checking now `/users/:uid` endpoint, and I receive proper _status_.
For example on local machine, only my account is online (uid:1), it shows _online_ for my account, and _offline_ for any other account.

NodeBB: v1.0.3

**Comment by ricoud** [comment]
You mean `v1/users/:uid`
Here is a picture of my dev environment. Can't  understand what's wrong. `api/users/userslug` says _offline_ and `api/v1/users/:uid` says _online_ . Got same answers for any user I tested.
Nodebb v 1.0.3
nodebb-plugin-write-api 4.2.0
nodebb-plugin-ns-api 2.0.1
Thanks in advance for your advices

![apinodebb](https://cloud.githubusercontent.com/assets/11999081/15552495/f4e974d8-22ba-11e6-8b0b-89c416a48e93.jpg)
